---
clients:
- code: shrimp_shells
  name: Shrimp Shells
  industry: restaurant
  subdomain: shrimp-shells
  contact:
    email: info@shrimpshells.com
  services:
    mattermost:
      enabled: true
      team_name: Shrimp Shells Team
      admin_username: shrimp_shells_admin
      admin_email: info@shrimpshells.com
  status: trial
  created_at: '2025-11-13 14:00:57 +0900'
  # n8nはPlatformインスタンスでプロジェクト機能を使用して管理
